### ISSUE TITLE
Events that begin at midnight show up on the previous day in the month and year templates.

### ISSUE THREAD

**Issue by waustin** [bartekgorny/django-schedule#1]
Any time I create an event that begins at midnight it shows up as an occurrence for the previous day. 
The error appears to be in  the _get_day_range and next_day methods of the Day class in periods.py

```
def _get_day_range(self, date):
    if isinstance(date, datetime.datetime):
        date = date.date()
    start = datetime.datetime.combine(date, datetime.time.min)
    #end = start + datetime.timedelta(days=1)
    end = datetime.datetime.combine(date, datetime.time.max)
    return start, end

def next_day(self):
    return Day(self.events, self.start + datetime.timedelta(days=1))
```

**Comment by bartekgorny** [comment]
True; I just committed an experimental bugfix (in a branch, not to mess) - see https://github.com/bartekgorny/django-schedule/commit/14700597061d440c7eb4f4d3237a2f9fc82d3d69

**Comment by bartekgorny** [comment]
ok
