### ISSUE TITLE
RuleForm clean_params seems overly restrictive

### ISSUE THREAD

**Issue by mark0978** [bartekgorny/django-schedule#5]
https://github.com/bartekgorny/django-schedule/blob/master/schedule/forms.py#L47

There is a line in clean_params that looks like:

```
param = (str(param[0]), [int(p) for p in param[1].split(',')])
```

This line prevents things like 

byweekday:SU,MO,TU,WE,TH,FR,SA

My quick fix (which is somewhat to permissive) was to change the `int(p)` to just  `p`.  I'm guessing the better fix would be to look for places where the RRULE_WEEKDAYS are valid and check the names there?

Would it make more sense to try to pass this down to the dateutil code, and see if it likes it instead of doing this kind of work outside the dateutil code?  If we just tried to construct an rrule object, could we pick up on the exception from dateutil to know if we had a valid format?

**Comment by bartekgorny** [comment]
I think so - please go ahead.

**Comment by tgecho** [comment]
This also effects rules such as "byweekday:SU(2)" which are listed in the wiki as valid. I like the idea of leveraging dateutil.

**Comment by tgecho** [comment]
So I tried just having clean_params run the field through get_params from the actual Rules model... at first glance it seems to work really well. I'm not sure if there are any unintended side effects, but here's the commit if you want to take a look: https://github.com/tgecho/django-schedule/commit/f9178140bdb7f286f4438402e80e9d9a5f6a0560

**Comment by bartekgorny** [comment]
I merged it (sorry for the delay); I'll keep this issue open for a while untill we are sure everything works.
