### ISSUE TITLE
Template error: 'BlockNode' object has no attribute 'context'

### ISSUE THREAD

**Issue by mixmastamyk** [bartekgorny/django-schedule#8]
Received this error on the day view until I added the following line:
    {% extends "schedule/base.html" %}
to:
    project_sample/schedule/templates/schedule/_dialogs.html

**Comment by sontek** [comment]
I have fixed this in my branch if you want to pull from there. I've created a pull request for this repo but don't know when he'll get my changes in.  https://github.com/sontek/django-schedule

The reason it was happening is because _dialogs.html was being included inside the {% block body %}

**Comment by mixmastamyk** [comment]
Ok, thanks.
